### ISSUE TITLE
Only one mic is working?

### ISSUE THREAD

**Issue by kunallanjewar** [shivasiddharth/custom-voice-hat#2]
I followed all instruction and made sure i followed them currently, including the wiring of both microphones and the amp.

However, when I run following command, I can only see one mic working. I was wondering if both mics work for you?

`arecord -D plughw:0 -c2 -r 48000 -f S32_LE -t wav -V stereo -v file_stereo.wav`

**Comment by shivasiddharth** [comment]
Sorry for getting back late. Missed this somehow.
I had the same suspicion , so i checked out the original AIY HAT that i have with me. Even in that, two channels are multiplexed into one.
